version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
      - run:
          command: ./manage.py test
          name: Test
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/pymcbdsc.egg-info/
            - ~/dist/
      - store_artifacts:
          path: dist
          destination: package
  python/test:
    executor: python/default
    steps:
      - run:
          command: ./manage.py test
          name: Test


workflows:
  main:
    jobs:
      - build
      - python/test:
          name: test-py3.5
          version: "3.5"
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
      - python/test:
          name: test-py3.6
          version: "3.6"
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
      - python/test:
          name: test-py3.7
          version: "3.7"
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
      - python/test:
          name: test-py3.8
          version: "3.8"
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
      - python/test:
          name: test-py3.9
          version: "3.9"
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
