version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./setup.py bdist_wheel
          name: Build
      - run:
          command: ./manage.py test
          name: Test
      - store_artifacts:
          path: dist
          destination: package

workflows:
  main:
    jobs:
      - build-and-test
