version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Generate requirements.txt
          command: python manage.py requires -o requirements.txt
      - python/install-packages:
          pkg-manager: pip
      - python/dist
      - run:
          command: ./setup.py test
          name: Test
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - pymcbdsc.egg-info/
            - dist/
      - store_artifacts:
          path: dist
          destination: package
  python/test:
    executor: python/default
    steps:
      - run:
          command: ./setup.py test
          name: Test
  register:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Generate requirements.txt
          command: python manage.py requires -o requirements.txt
      - restore_cache:
          key: v1-{{ .Branch }}-{{ .Revision }}
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: ./manage.py vercheck -e CIRCLE_TAG
          name: check version and tag
      - run:
          command: pip install twine
          name: install twine
      - run:
          command: |
            echo -e "[pypi]" > ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
          name: Create .pypirc
      - run:
          command: twine upload dist/*
          name: Upload


workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - python/test:
          name: test-py3.5
          version: "3.5"
          requires:
            - build
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
          filters:
            tags:
              only: /.*/
      - python/test:
          name: test-py3.6
          version: "3.6"
          requires:
            - build
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
          filters:
            branches:
              only:
                - main
            tags:
              only: /.*/
      - python/test:
          name: test-py3.7
          version: "3.7"
          requires:
            - build
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
          filters:
            branches:
              only:
                - main
            tags:
              only: /.*/
      - python/test:
          name: test-py3.8
          version: "3.8"
          requires:
            - build
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
          filters:
            branches:
              only:
                - main
            tags:
              only: /.*/
      - python/test:
          name: test-py3.9
          version: "3.9"
          requires:
            - build
          pkg-manager: pip
          pip-dependency-file: pymcbdsc.egg-info/requires.txt
          setup:
            - restore_cache:
                key: v1-{{ .Branch }}-{{ .Revision }}
          filters:
            tags:
              only: /.*/
      - register:
          name: register
          requires:
            - test-py3.5
            - test-py3.6
            - test-py3.7
            - test-py3.8
            - test-py3.9
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
